### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by crutchcorn** [EvodiaAut/vue-marquee-text-component#42]
Funnily, right after we published v`2.1`, I migrated my app to use Vite for SSR. 

After doing so, I started getting the following errors:

```
ReferenceError: document is not defined
    at addStyle (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:779:22)
    at addStylesToDom (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:763:20)
    at addStylesClient (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:717:3)
    at Object.e7b3 (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:2183:14)
    at __webpack_require__ (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:21:30)
    at Object.c45f (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:1870:499)
    at __webpack_require__ (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:21:30)
    at Module.fb15 (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:2352:74)
    at __webpack_require__ (C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:21:30)
    at C:\Users\crutchcorn\git\Twitch\streampods\node_modules\vue-marquee-text-component\dist\MarqueeText.common.js:85:18
```

However, if I import the `src` file itself:

```
import MarqueeText from 'vue-marquee-text-component/src/components/MarqueeText.vue';
```

Rather than the final build, I get no such errors.

As such, this seems to me like a build setup error.

**Comment by EvodiaAut** [comment]
Before I released v2.0.1 (yarn link), I included it on 2 other vue3 projects and it worked?
Have you tried [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies)?

**Comment by crutchcorn** [comment]
Were you testing with SSR apps? It worked fine for my app prior to being SSR

I'm using Vite SSR with default `@vite/plugin-vue` configuration

**Comment by leosin** [comment]
> 

in nuxt 3 have same issue

**Comment by EvodiaAut** [comment]
Anyone have an idea why?

**Comment by d4rkr3pt0r** [comment]
@EvodiaAut @crutchcorn 
```
<client-only>
	<marquee-text>
	Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna.
	</marquee-text>
</client-only>
components: {
	MarqueeText: () => import('vue-marquee-text-component'),
},
```

**Comment by EvodiaAut** [comment]
@d4rkr3pt0r @crutchcorn 
Looks like we can close the ticket?

**Comment by TheAlexLichter** [comment]
> @d4rkr3pt0r @crutchcorn Looks like we can close the ticket?

I think an ESM build would be sufficient to avoid this error. When using the Vue file itself for importing, no issue arises. See [this codesandbox](https://codesandbox.io/s/nuxt-discussion-4924-xfuxur)

Old: ~~I would suggest to change the logic so platform-specifc APIs are only access when rendering the component, not already during the import! ☺️ See [my post](https://blog.lichter.io/posts/universal-ssr-vue-component-guide/#window%2C-document%2C-and-friends---platform-specific-apis) for more info.~~
